import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { SyntheticEvent } from 'react';
import Image from 'next/image';

export default function Home()
{
  const router = useRouter();

  const handleClick = (e: SyntheticEvent<any>) =>
  {
    e.preventDefault();
    router.push('login')
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Login app with hash security</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/japGhost.png" />
      </Head>

      <main className={styles.main}>
        <Image src="/japGhost.png" alt="App logo" width={300} height={400} />
        <h1 className={styles.title}>
          Welcome to my Login app
        </h1>

        <p className={styles.description}>
          Get started by clicking on the button below
        </p>

        <button className="btn solid" onClick={handleClick}>Go To login</button>
      </main>

      <footer className={styles.footer}>
        Made with love ❤  by Badri Tibourtine
      </footer>
      <style jsx>{`
        @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800&display=swap");

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        .btn {
          width: 150px;
          background-color: #dd1818;
          border: none;
          outline: none;
          height: 49px;
          border-radius: 49px;
          color: #fff;
          text-transform: uppercase;
          font-weight: 600;
          margin: 10px 0;
          cursor: pointer;
          transition: 0.5s;
        }

        .btn:hover {
          background-color: #AA0505;
        }
      `}</style>
    </div>
  )
}
